### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ProbablyRaging** [ProbablyRaging/CreatorBot#1]
### Overall

- [ ] [Partial intent for DM channels](https://discordjs.guide/additional-info/changes-in-v13.html#dm-channels)
- [ ] [Strings](https://discordjs.guide/additional-info/changes-in-v13.html#strings)
- [ ] [Sending messages, embeds, files, etc](https://discordjs.guide/additional-info/changes-in-v13.html#sending-messages-embeds-files-etc)
- [ ] [Collectors](https://discordjs.guide/additional-info/changes-in-v13.html#collectors)
- [ ] [Thing#thingId](https://discordjs.guide/additional-info/changes-in-v13.html#thing-thingid)
- [ ] [Client#message](https://discordjs.guide/additional-info/changes-in-v13.html#client-message)
- [ ] [Bitfields / Permissions](https://discordjs.guide/additional-info/changes-in-v13.html#bitfields-permissions)
- [ ] [ActivityType](https://discordjs.guide/additional-info/changes-in-v13.html#activitytype)
- [ ] [Channel#type](https://discordjs.guide/additional-info/changes-in-v13.html#channel-type)
- [ ] [ClientUser#setPresence](https://discordjs.guide/additional-info/changes-in-v13.html#clientuser-setpresence)?
- [ ] [Guild#fetchBans](https://discordjs.guide/additional-info/changes-in-v13.html#guild-fetchbans)?
- [ ] [Guild#member](https://discordjs.guide/additional-info/changes-in-v13.html#guild-member)?
- [ ] [Guild#owner](https://discordjs.guide/additional-info/changes-in-v13.html#guild-owner)?
- [ ] [Guild#voice](https://discordjs.guide/additional-info/changes-in-v13.html#guild-voice)?
- [ ] [GuildChannel#createOverwrite](https://discordjs.guide/additional-info/changes-in-v13.html#guildchannel-createoverwrite)
- [ ] [GuildChannel#overwritePermissions](https://discordjs.guide/additional-info/changes-in-v13.html#guildchannel-overwritepermissions)
- [ ] [GuildChannel#setTopic](https://discordjs.guide/additional-info/changes-in-v13.html#guildchannel-settopic)
- [ ] [GuildChannel#updateOverwrite](https://discordjs.guide/additional-info/changes-in-v13.html#guildchannel-updateoverwrite)
- [ ] [GuildMember#ban](https://discordjs.guide/additional-info/changes-in-v13.html#guildmember-ban)
- [x] [GuildMember#hasPermission](https://discordjs.guide/additional-info/changes-in-v13.html#guildmember-haspermission)
- [ ] [GuildMember#lastMessage](https://discordjs.guide/additional-info/changes-in-v13.html#guildmember-lastmessage)
- [ ] [GuildMember#presence](https://discordjs.guide/additional-info/changes-in-v13.html#guildmember-presence)
- [ ] [GuildMemberManager#ban](https://discordjs.guide/additional-info/changes-in-v13.html#guildmembermanager-ban)
- [ ] [Message#delete](https://discordjs.guide/additional-info/changes-in-v13.html#message-delete)
- [ ] [WebhookClient](https://discordjs.guide/additional-info/changes-in-v13.html#webhookclient)

### message.js

- [ ] remove marketplace code
- [ ] remove rank reminder code
- [ ] possibly remove suggestions code

### index.js
- [ ] remove sticky button code
- [ ] remove sticky code
